### PR TITLE
Update Santa Cruz image URL

### PR DESCRIPTION
**Pull request by bendrucker**
Thanks for publishing this site! Have thought about making something similar before and a 🚲 friend passed this along. The GGB webcam is a bit of a pain, but I wrote this way back and it still works:

https://github.com/bendrucker/golden-gate

In any case...

<hr>

The USGS now publishes these images to a different S3 bucket. The old bucket no longer resolves.

```
$ curl --head https://argusdata.s3.amazonaws.com/dreaminn/latest/c1_snap.jpg

HTTP/1.1 403 Forbidden
x-amz-request-id: FF65FEDC9AB84249
x-amz-id-2: xPhr5wN/wbpXQ7HY96dewjvYfzTLgaN5X6KgTlUfPBY8n/b6twS8UmdSK1HQN8wDJgNAzrVqsKc=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Thu, 04 Jun 2020 20:46:31 GMT
Server: AmazonS3

$ curl --head https://cmgp-coastcam.s3-us-west-2.amazonaws.com/cameras/dreaminn/latest/c1_snap.jpg

HTTP/1.1 200 OK
x-amz-id-2: K77CjhpU3+QurDge/OAkQ6SiOcV0ed7zlY/62JbvtDwHEtRR8pEEwy+OUtpt94g6uuCvMk7gl3s=
x-amz-request-id: 3CA16C5F869EAF52
Date: Thu, 04 Jun 2020 20:46:41 GMT
Last-Modified: Thu, 04 Jun 2020 20:42:05 GMT
ETag: "83470f2bde33aa2c64512fe299f7affb"
x-amz-meta-s3cmd-attrs: uid:0/gname:root/uname:root/gid:0/mode:33279/mtime:1591303276/atime:1591303276/md5:83470f2bde33aa2c64512fe299f7affb/ctime:1591303276
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 464864
Server: AmazonS3
```

### CODE REVIEW

**Comment by t1merickson** [comment]
@bendrucker thanks Ben!  reviewing this and also adding a few other fixes I've been procrastinating on.

**Comment by t1merickson** [comment]
@bendrucker  Forgive me, I'm useless with javascript. Any thought on how we might merge in your code for the JPEG stream of the GGB cam?  Would we need to prop up an API on a server? Given the way netlify serves this site statically 

If you have time I would of course welcome a PR 🤝

**Comment by bendrucker** [comment]
Hey, happy to help with that! I went to extra trouble to be able to get an image directly without needing an actual browser in that package. 

You can embed the whole player in an iframe and get a moving version. That's how they're used here:

https://www.parksconservancy.org/parks/golden-gate-bridge-live-webcams

They seem to be using motion JPEG and updating an `` tag via JavaScript, really weird stuff

**Comment by t1merickson** [comment]
Yep, so, my struggle with that cam is the iframe they use comes with a baked in 'foggy' grey frame thing, with controls, and a fixed size. I wasn't able to manipulate the size of the frame or load just the JPEG stream image.  

If you've found a way to pull just the JPEG stream, could we add it to this site's repo somehow?  Even if it was just an image pulled at the time of page load?

**Comment by bendrucker** [comment]
Yeah totally! The project is pretty Node oriented but I can clean it up a bit so that it transpiles into something reasonable that you could embed via a `<script>` tag and then add the image data programmatically. Will spend some time on that and get back to you.

**Comment by t1merickson** [comment]
That would be massively appreciated Ben!! the site gets thousands of hits each month and adding this cam would be greatly appreciated by many.   :)

**Pull request merged**
